{% set version = "3.2.2" %}
{% set name = "statsd" %}
{% set sha256 = "84f2427ef7b8ffab28cdb717933f6889d248d710eee32b5eb79e3fdac0e374dd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - nose
    - python
    - mock
  commands:
    - python -m nose statsd

about:
  home: https://github.com/jsocol/pystatsd
  license: MIT
  summary: A Python client for statsd
  license_file: LICENSE
  doc_url: http://statsd.readthedocs.io
  dev_url: https://github.com/jsocol/pystatsd
  license_family: MIT

extra:
  recipe-maintainers:
    - bollwyvl
