travis:
  secure:
    BINSTAR_TOKEN: IahcLmcttYhPAYgY2TXniXAFsuKjw0g22LKSdmF7rq1qnOcps9I093X2vUE9wRzFTGZngEXtn5ot9GV/fUWvMuXhOLAKp8fiA8C5gh/uYtm6wv9doZm9i3EI7oMnfXDRdNvbXhQCYKeMmwPMyH2Fedxu1sO7fV5I/HsWayqXbfEBRON3eWt6TKKIAGY8D8P/Nf6PcMR3qhIuIbImo7x7Z2rvrxDlMgUaPDpscUvHqqHVt0rFByXTLMGGroSjr2W+vVig7qh33GugQPqAvBbwTjhir9CFs6pah91q1eNAEaIABmym6YMdyX0Ru90m0NcXzVgVszC+DVecnIQsFCGg97TICEcufgwayzunOji1O8wdCaeJjgvs1hb8MykDklaqEbfkl37voXNhivGeiJmKNx3FJ+aP3EW0cD3Abw8TKU1tdOtdLfR+PAG2fDgq3VQ2vMIDXzJW74anywpxCgvar6NGz09D377xZzZCLm5bUmKoI6ivaKmo0SG6zAVAHq2fdN7i1lkasckPwGEIHRTKxpaT2COjgKHEMqGeqz7FwYPyxj03Zj96mLa77VKwkBAjE0wxgEWO34FF5jD4jd1S8EGhAFXnAngq8FAMw2fnI9aVOblVEVIVWdnMQ0QMj2R2nLWRalri8dIHniGRFONamOmDPFFiyyXGEfrC2kM2ykk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
