travis:
  secure:
    BINSTAR_TOKEN: bMfOYMPg6bmFalzfktxEv3PIpdDVA4PR0I+cFgleRgviH3nggArDlh+HwdG6GjT/bEW0LWhJwhIUc+L5jVevknIlCMLbDJIqw4oVRlo/Ib8uNdhPZQONPTY/EnacZoo+dqKt6PX8N7qtNFQB1dTm7nuu3haOKYhQfaUC+jBXwwCBgeo04Nl/gkMUKAj16vYJYDAw1EKRdKlC9WpGuxe3tGQ9EtjXWS0kPmmo2urMsoEWlgu/WGuY/4zUkiHwHeKp8q+LtX3WTgywTTvQkJxWKcTxeWWAb1YLFHfyiUk2lROHJFUX2V/SL1NqBjsNFHENcNXFdvybNbt5w6QQ9vTeaXX3A6rV6isnanNuFaMa0hrTmJ/xGqOVYXsix5eqbbbnfwJ5VgAbuL8DwZUg9C1efF+hAN2Sz/RhPE2jW1VCY0oMyYFs0exVLnPup2p0xW6ESkhrCRjXJrhkfGoMYSGPCny5bsEcex5L93Ri70xiS7hXDikd3w4BPLM2nVfYSw7xcQyWEHCJtH2ehSo310jeXRJtYtdzqzPMExKEonnpCvUOqhxgpEPQ9+zF2UYSFabW0HuIIZ6X1KGWgO8lfQehMR+uEW0pAQaSd3Q86duuUIZDXJJ28/u+73NitWHAOR58L+ky4bbLdLL2MFdXUWfdl91IIfEE5YhjzS41mmjaXkA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
