travis:
  secure:
    BINSTAR_TOKEN: ozSZ/yHrw/wIsuuIOeOz4v1g542+D5SuoEpP5RxKbMe1C7kgb/ojyFIdLs/bBjUOkZiCm8IeKvahDXHgycd7BVcJq+p11uxMNpKOyMTdYF1okrnKNhGah5i7gclMHHTcSOk+eiqnAeSmSQPfqb3ujiAtZ4rnsRe9eWdLcWcc1cJI2d+wqksWZvmR1rMVpzjoRJSdD0ejyD85YoaaLhyEUkzkMyf3F2GJk1eb2uj60P6A9yR0T63OFm5pePslqeLBB83hCNFPumwiulVhGW0BaSL9/RiWrM5tAE+fr4oVU4PbjAvRUjY9xdlmwRZUtc2q/OVRYo+9Cy0qrYVIBtDJncr/FcVDB0ldJ+9pj5h57lSk8kz5jMBAASsAyIzxnjI7GAVNaiKNdtZWkaZ4eLECWAtdPZcWPwWNy5LaKoeirWoIKhExj92pJeByEvtzptoPB59Y9CMizSDOk8+SZbK9zl0iNiryo8lgjLhrDUFuaL6rbkzeE0e3rN7VXmz1b9VRnT8vcIydfxvTudjgqhOD9mbl6e8OiG40YvezqInEDyzfz9dun/mJKLH1sRyQCo2LcSRzbnCm7BlCd270RLgBMvNJ10cOx+ymrtfG89yF+B5rIHRvaCSKHREBBEecOMYW0j59H7Fts0ZHaa3EM6O9I09oBKz0DYbfUMaEvPevaw4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
